{
 "title": "Kubernetes Cluster Filesystem Metrics",
 "description": "file descriptors, used, available metrics",
 "time": { "from": "2019-01-02T02:01:45.171Z", "to": "2019-01-03T02:01:45.171Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu{job=\"kubernetes-service-endpoints\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu{job=\"kubernetes-service-endpoints\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "File Descriptors (All Nodes)",
   "type": "graph",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "File Descriptors (Single Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{job=\"kubernetes-service-endpoints\",instance=~\"$node:$port\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Used (Single Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{job=\"kubernetes-service-endpoints\",instance=~\"$node:$port\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"} - node_filesystem_avail{job=\"kubernetes-service-endpoints\",instance=~\"$node:$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available (Single Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{job=\"kubernetes-service-endpoints\",instance=~\"$node:$port\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}